In [11]:
footsizeToLED = [[0, 0], [1, 0], [2, 1], [3, 1], [4, 2], [5, 2], [6, 2], [6, 3], [7, 3], [8, 3]]
sex = 1

In [61]:
def updateFootsize(trueVertPos, trueHorizPos, estVertPos, estHorizPos, footsize):
    horizIdxRange = [[0, 1], [2, 3], [4, 6], [7, 9]]
    good = False
    #print("\nChecking if we need to update footsize.")
    #print("Old footsize: " + str(footsize))
    #print("True LED positions are (" + str(trueVertPos) + ", " + str(trueHorizPos) + ").")
    #print("Estimated LED positions are (" + str(estVertPos) + ", " + str(estHorizPos) + ").")

    if (trueVertPos == estVertPos and trueHorizPos == estHorizPos):
        footsize = footsize
        good = True
    elif ((trueHorizPos < 3) and (footsizeToLED[trueVertPos][1] == trueHorizPos)):
        footsize = trueVertPos-sex+5
        good = True
    elif ((footsizeToLED[trueVertPos+1][1] == 3)):
        footsize = trueVertPos+1-sex+5
        good = True
    else:
        # [4,0] goes to [2,1]. Want [3,1]
        if ((trueVertPos - footsizeToLED[horizIdxRange[trueHorizPos][0]][0]) == -1):
            footsize = horizIdxRange[trueHorizPos][0]-sex+5
        elif ((trueVertPos - footsizeToLED[horizIdxRange[trueHorizPos][0]][0]) < -1):
            footsize = horizIdxRange[trueHorizPos-1][0]-sex+5
        elif ((trueVertPos - footsizeToLED[horizIdxRange[trueHorizPos][1]][0]) == 1):
            footsize = horizIdxRange[trueHorizPos][1]-sex+5
        elif ((trueVertPos - footsizeToLED[horizIdxRange[trueHorizPos][1]][0]) > 2):
            footsize = horizIdxRange[trueHorizPos+1][1]-sex+5

    return footsize, good
    #print("New footsize: " + str(footsize))
    #print("Which is associated with LED positions (" + str(footsizeToLED[footsize+sex-5][0]) + ", " + str(footsizeToLED[footsize+sex-5][1]) + ").")

In [64]:
import pandas as pd
import numpy as np

old_f = []
new_f = []
des_p = []
est_p = []
new_p = []
good_list = []
same_width = []
len_diff = []
width_diff = []
for i, est_params in enumerate([[0, 0], [1, 0], [2, 1], [3, 1], [4, 2], [5, 2], [6, 2], [6, 3], [7, 3], [8, 3]]):
    footsize = i-sex+5
    for true_vert in range(max(est_params[0]-3, 0), min(est_params[0]+3, 8)):
        for true_horiz in range(max(est_params[1]-2, 0), min(est_params[1]+2, 3)):
            new_footsize, good = updateFootsize(true_vert, true_horiz, est_params[0], est_params[1], footsize)
            if new_footsize == footsize: continue
            if good: continue # temp
            old_f.append(footsize)
            est_p.append(footsizeToLED[footsize+sex-5])
            des_p.append([true_vert, true_horiz])
            new_f.append(new_footsize)
            new_p.append(footsizeToLED[new_footsize+sex-5])
            good_list.append(good)
            len_diff.append(np.abs(footsizeToLED[new_footsize+sex-5][0] - true_vert))
            width_diff.append(np.abs(footsizeToLED[new_footsize+sex-5][1] - true_horiz))
            same_width.append(footsizeToLED[new_footsize+sex-5][1] == true_horiz)

#results_all = pd.DataFrame({'old footsize': old_f, 'new footsize': new_f, 'old LED pos': est_p, 'desired LED pos': des_p, 'new LED pos': new_p, 'correct': good_list})
results = pd.DataFrame({'old footsize': old_f, 'new footsize': new_f, 'desired LED pos': des_p, 'new LED pos': new_p, 'len diff': len_diff, 'width diff': width_diff, 'same width': same_width})

In [ ]:
# [[0, 0], [1, 0], [2, 1], [3, 1], [4, 2], [5, 2], [6, 2], [6, 3], [7, 3], [8, 3]]

In [65]:
results[results['same width']]

,old footsize,new footsize,desired LED pos,new LED pos,len diff,width diff,same width
0,4,6,"[1, 1]","[2, 1]",1,0,True
1,4,5,"[2, 0]","[1, 0]",1,0,True
3,5,6,"[1, 1]","[2, 1]",1,0,True
5,6,5,"[2, 0]","[1, 0]",1,0,True
6,6,8,"[3, 2]","[4, 2]",1,0,True
8,6,7,"[4, 1]","[3, 1]",1,0,True
11,7,6,"[1, 1]","[2, 1]",1,0,True
13,7,5,"[2, 0]","[1, 0]",1,0,True
15,7,8,"[3, 2]","[4, 2]",1,0,True
16,8,6,"[1, 1]","[2, 1]",1,0,True
18,8,5,"[2, 0]","[1, 0]",1,0,True
21,8,7,"[4, 1]","[3, 1]",1,0,True
23,9,5,"[2, 0]","[1, 0]",1,0,True
25,9,8,"[3, 2]","[4, 2]",1,0,True
27,9,7,"[4, 1]","[3, 1]",1,0,True
29,10,8,"[3, 2]","[4, 2]",1,0,True
31,10,7,"[4, 1]","[3, 1]",1,0,True
33,11,8,"[3, 2]","[4, 2]",1,0,True
34,11,7,"[4, 1]","[3, 1]",1,0,True
35,12,7,"[4, 1]","[3, 1]",1,0,True

In [ ]:
# [[0, 0], [1, 0], [2, 1], [3, 1], [4, 2], [5, 2], [6, 2], [6, 3], [7, 3], [8, 3]]

In [66]:
results[results['same width'] == False] # UPDATE LOGIC: [4,0] should become [3,1]

,old footsize,new footsize,desired LED pos,new LED pos,len diff,width diff,same width
2,5,4,"[0, 1]","[0, 0]",0,1,False
4,6,4,"[0, 1]","[0, 0]",0,1,False
7,6,7,"[4, 0]","[3, 1]",1,1,False
9,7,4,"[0, 1]","[0, 0]",0,1,False
10,7,6,"[0, 2]","[2, 1]",2,1,False
12,7,6,"[1, 2]","[2, 1]",1,1,False
14,7,6,"[2, 2]","[2, 1]",0,1,False
17,8,6,"[1, 2]","[2, 1]",1,1,False
19,8,6,"[2, 2]","[2, 1]",0,1,False
20,8,7,"[4, 0]","[3, 1]",1,1,False
22,8,7,"[5, 0]","[3, 1]",2,1,False
24,9,6,"[2, 2]","[2, 1]",0,1,False
26,9,7,"[4, 0]","[3, 1]",1,1,False
28,9,7,"[5, 0]","[3, 1]",2,1,False
30,10,7,"[4, 0]","[3, 1]",1,1,False
32,10,7,"[5, 0]","[3, 1]",2,1,False

In [63]:
results_all.to_csv('all_results.csv')